### PR TITLE
:hammer: fix atom 1.13 deprecation warnings

### PR DESCRIPTION
**Pull request by cloud-walker**
I've followed the *atom's deprecation cop* instructions, and seems to working fine, lemme know!

### CODE REVIEW

**Comment by jesseleite** [comment]
Interesting, I assume this solves issue #19?

Also is Atom going towards something like BEM with those double dashed `syntax--selectors`, etc.?

**Comment by cloud-walker** [comment]
yes I think so, there was a blog post about it not so long ago...

BTW I need a review, I'm not an expert about atom plugins

**Comment by cloud-walker** [comment]
I've found the blog post

http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html

**Comment by jesseleite** [comment]
Great thanks for info, I'll definitely look into this and review 👌

**Comment by jesseleite** [comment]
Thanks @cloud-walker for the help!  I reverted the work you did in `ui-modifications`, because those classes aren't supposed to have `syntax--`.  Seems some of those styles don't work in 1.13 though, so I have some research to do.  But nice work on the base.less file, thanks again!

**Pull request merged**
