### PR TITLE
Adding border to the gutter

### PR DESCRIPTION
**Pull request by dustinsanders**
Added border to gutter to make it easer to see where the text starts.

### CODE REVIEW

**Comment by jesseleite** [comment]
This was intentional to better match how One Dark handles gutter styling.  I'm curious if you could post screenshot though.

**Comment by dustinsanders** [comment]
Here's a screenshot, the gutter border is subtle but I think it helps with knowing where the cursor is in relation to the beginning of the line.
screen shot 2016-01-22 at 10 27 18 am

**Comment by jesseleite** [comment]
Ah I see.  Interesting.  I'm going to close this PR, as I intended there to be no border, similar to One Dark.  This whole thing is an intentional One Dark variant really.  That said, feel free to add your own style overrides to your stylesheet :)

example

**Comment by dustinsanders** [comment]
@JesseLeite What is the package you are using to get the vertical guidelines for each block of code?

**Pull request closed without merging**
